version: '3.8'

services: 
    backend:
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        ports:
            - "8083:8083"
    frontend:
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
        ports:
            - "3000:3000"
        links:
            - "backend:be"