// // Generated by Selenium IDE

// const { Builder, By, Key, until } = require('selenium-webdriver')
// const assert = require('assert')

// describe('done', function() {
//   // this.timeout(30000)
//   let driver
//   let vars
//   beforeEach(async function() {
//     driver = await new Builder().forBrowser('chrome').build()
//     vars = {}
//   })
//   afterEach(async function() {
//     await driver.quit();
//   })
//   it('done', async function() {
//     await driver.get("http://localhost:8081/")
//     await driver.manage().window().setRect({ width: 1200, height: 842 })
//     await driver.findElement(By.css(".list-group-item:nth-child(1)")).click()
//     await driver.findElement(By.linkText("Edit")).click()
//     await driver.findElement(By.id("title")).click()
//     await driver.findElement(By.id("title")).sendKeys("Task 3")
//     await driver.findElement(By.css(".badge-success")).click()
//     await driver.findElement(By.linkText("Tasks")).click()
//   })
// })
